# Generated by Django 5.0.3 on 2024-03-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flower102Interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowers',
            name='flower_name',
        ),
    ]
